schema Data:
    $all: int = 1
    $any: int = 2
    $map: int = 3
    $filter: int = 4
    $schema: int = 5
    $mixin: int = 6
    $import: int = 7
    $pass: int = 8
    $in: int = 9
    $and: int = 10
    $or: int = 11
    $is: int = 12
    $not: int = 13
    $return: int = 14
    $check: int = 15
    $assert: int = 16
    $if: int = 17
    $else: int = 18
    $elif: int = 19
    $for: int = 20
    $final: int = 21
    $relaxed: int = 22
    $rule: int = 23
    $def: int = 24

data = Data {}
