#!/bin/sh

# Stop on error.
set -e

# kclvm_cli path
kclvm_cli_bin=`which kclvm_cli`
kclvm_install_dir=$(cd `dirname $0`/..; pwd)

# check kclvm_cli
if [ -z "$kclvm_cli_bin" ]; then
    echo "kclvm cli not found!"
    exit 1
fi

export PYTHONPATH=$kclvm_install_dir/lib/site-packages
export KCLVM_CLI_BIN_PATH=$kclvm_install_dir/bin
# Only for v0.4.x, all CLIs will be unified after v0.5.x
case $1 in
    "version" | "--version" | "-v" | "-V")
        $kclvm_cli_bin version
        ;;
    *) $kclvm_cli_bin run "$@"
        ;;
esac
