#!/bin/sh

# Stop on error.
set -e

# kclvm_cli path
install_dir=$(cd `dirname $0`/..; pwd)
export PYTHONPATH=$install_dir/lib/site-packages
export KCLVM_CLI_BIN_PATH=$install_dir/bin
kclvm_cli_bin=$install_dir/bin/kclvm_cli
$kclvm_cli_bin fmt "$@"
