data1 = [
    if True:
        "value1"
        1
    elif True:
        "value2"
        2
    elif True:
        "value3"
        3
    else:
        "value4"
        4
]
data2 = [
    if False:
        "value1"
        1
    elif True:
        "value2"
        2
    elif True:
        "value3"
        3
    else:
        "value4"
        4
]
data3 = [
    if False:
        "value1"
        1
    elif False:
        "value2"
        2
    elif True:
        "value3"
        3
    else:
        "value4"
        4
]
data4 = [
    if False:
        "value1"
        1
    elif False:
        "value2"
        2
    elif False:
        "value3"
        3
    else:
        "value4"
        4
]
