[package]
name = "kclvm_cli"
version = "0.11.2"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "kclvm_cli"

[profile.release]
rpath = true
panic = "unwind"
opt-level = "z"  # Optimize for size.
lto = true
