c = {"a": 1, b = {"a": "b"}}
_access = test.ServiceAccess {
    iType = "kkkkkkk"
    sType = dsType
    TestStr = ["${test_str}"]
    ports = [80, 443]
    booltest = True
}

b = {"c": 2}
d = {
    e: {
        f: {g = 3}
    }
}
_access3 = test.ServiceAccess {
    iType = "kkkkkkk"
    sType = dsType
    TestStr = ["${test_str}"]
    ports = [80, 443]
    booltest = True
}

_access5 = {iType = "dddddd"}
