#!/bin/sh

# Stop on error.
set -e

# kclvm_cli path
install_dir=$(cd `dirname $0`/..; pwd)
export PYTHONPATH=$install_dir/lib/site-packages
export KCLVM_CLI_BIN_PATH=$install_dir/bin
kclvm_cli_bin=$install_dir/bin/kclvm_cli
# Only for v0.4.x, all CLIs will be unified after v0.5.x
case $1 in
    "version" | "--version" | "-v" | "-V")
        $kclvm_cli_bin version
        ;;
    *) $kclvm_cli_bin run "$@"
        ;;
esac
