use std::{fs::remove_file, path::Path};

use crate::testing::{TestCaseInfo, TestOptions, TestResult, TestRun, flatten_case_coverage};
use anyhow::{Result, anyhow};
use kcl_ast::ast;
use kcl_driver::get_pkg_list;
use kcl_parser::get_kcl_files;
use kcl_parser::{ParseSessionRef, parse_file_force_errors};
use kcl_primitives::{DefaultHashBuilder, IndexMap};
use kcl_runner::ExecProgramArgs;
use kcl_runner::exec_program;
use std::collections::BTreeMap;
use std::time::Instant;

/// File suffix for test files.
pub const TEST_FILE_SUFFIX: &str = "_test.k";
/// Prefix for test suite names.
pub const TEST_SUITE_PREFIX: &str = "test_";

const TEST_MAIN_FILE: &str = "_kcl_test.k";
const TEST_CASE_RUN_OPTION: &str = "_kcl_test_case_run";
const TEST_MAIN_FILE_PREFIX: &str = r#"
# Auto generated by the kcl test tool; DO NOT EDIT!

_kcl_test_case_run = option("_kcl_test_case_run", type="str", default="")

"#;

pub struct TestSuite {
    /// Package path of the test suite. e.g. ./path/to/pkg
    pub pkg: String,
    /// List of normal files in the package.
    pub normal_files: Vec<String>,
    /// List of normal files without the `_test.k` suffix in the package.
    pub test_files: Vec<String>,
    // Map of test cases in the test suite.
    pub cases: IndexMap<String, TestCase>,
    // Flag indicating whether the test suite should be skipped.
    pub skip: bool,
}

impl TestRun for TestSuite {
    type Options = TestOptions;
    type Result = TestResult;

    /// Run the test suite with the given options and return the result.
    fn run(&self, opts: &Self::Options) -> Result<Self::Result> {
        let mut result = TestResult::default();
        // Skip test suite if marked as skipped or if there are no test cases.
        if self.skip || self.cases.is_empty() {
            return Ok(result);
        }
        // Generate the test main entry file.
        let main_file = self.gen_test_main_file()?;
        // Set up execution arguments. Coverage is opted into via
        // `opts.coverage`; we mirror it onto `ExecProgramArgs::coverage`
        // so the runner/evaluator know to record hits.
        let mut args = ExecProgramArgs {
            k_filename_list: self.get_input_files(&main_file),
            overrides: vec![],
            disable_yaml_result: true,
            coverage: opts.coverage,
            ..opts.exec_args.clone()
        };
        // Save the user argument options.
        let user_args = args.args;
        // Test every case in the suite.
        for (name, _) in &self.cases {
            args.args = vec![ast::Argument {
                name: TEST_CASE_RUN_OPTION.into(),
                value: format!("{:?}", name),
            }];
            args.args.append(&mut user_args.clone());
            let start = Instant::now();
            // Check if is the fast eval mode.
            let exec_result = exec_program(ParseSessionRef::default(), &args)?;
            // Check if there was an error.
            let error = if exec_result.err_message.is_empty() {
                None
            } else {
                Some(anyhow!("{}", exec_result.err_message))
            };
            // Check if the fail_fast option is enabled and there was an error.
            let fail_fast = error.is_some() && opts.fail_fast;
            // Per-case line hits. Empty unless coverage was requested —
            // in that case the runner drains the evaluator's coverage
            // state into `exec_result.coverage`, which we flatten into the
            // `<file>:<line>` convention the report expects.
            let line_hits = if opts.coverage {
                flatten_case_coverage(&exec_result.coverage)
            } else {
                Default::default()
            };
            // Merge into the aggregate report before we drop the per-case
            // map. Even failing cases contribute to coverage — a case
            // that panics halfway through still partially exercised the
            // code under test.
            result.coverage.merge(&line_hits);
            // Add test case information to the result.
            result.info.insert(
                name.clone(),
                TestCaseInfo {
                    log_message: exec_result.log_message.clone(),
                    duration: Instant::now() - start,
                    error,
                    line_hits,
                },
            );
            if fail_fast {
                break;
            }
        }
        // Remove the temp test main file. Cleanup failure isn't a test failure
        // — if another instance already deleted the file (parallel test
        // runs share a `main_file` path) we still want this run to report
        // its result.
        if opts.exec_args.debug == 0 {
            let _ = remove_file(main_file);
        }
        // Finalize coverage now that every case has run. We seed the
        // `executable_lines` map from a fresh parse of every non-generated
        // file in the package: the AST already gives us a precise
        // per-statement line number and we filter out the synthetic
        // `_kcl_test.k` dispatch shim so it doesn't inflate the
        // denominator.
        if opts.coverage {
            let executable = collect_executable_lines(&self.normal_files, &self.test_files);
            // The merge step above stored hits under absolute-path keys
            // (the evaluator normalizes filenames through the parser).
            // `executable` is keyed the same way — see
            // `collect_executable_lines` — so the lookup below finds
            // matches directly without further rewriting.
            result.coverage.finalize(&executable);
        }
        Ok(result)
    }
}

impl TestSuite {
    fn gen_test_main_file(&self) -> Result<String> {
        let test_codes = self
            .cases
            .keys()
            .map(|c| format!("if {} == '{}': {}()", TEST_CASE_RUN_OPTION, c, c))
            .collect::<Vec<String>>();
        let code = format!("{}{}", TEST_MAIN_FILE_PREFIX, test_codes.join("\n"));
        let path = Path::new(&self.pkg).join(TEST_MAIN_FILE);
        let test_main_file = path
            .to_str()
            .ok_or(anyhow!("{} is not found", TEST_MAIN_FILE))?;
        std::fs::write(test_main_file, code)?;
        Ok(test_main_file.into())
    }

    fn get_input_files(&self, main_file: &str) -> Vec<String> {
        // Construct test package files.
        let mut files = vec![];
        let mut normal_files = self.normal_files.clone();
        let mut test_files = self.test_files.clone();
        files.append(&mut normal_files);
        files.append(&mut test_files);
        files.push(main_file.into());
        files
    }
}

pub struct TestCase;

/// Walk every statement in each file (including statements nested inside
/// function / lambda / schema bodies) and record its start line as an
/// "executable line". Used to compute the coverage denominator without
/// re-running the evaluator.
///
/// File keys are normalized to their absolute, canonicalized form before
/// insertion so that they line up with the keys produced by the
/// evaluator's coverage recording — the parser stores `filename` on AST
/// nodes using whatever path it was given (often absolute after the
/// loader resolves relative inputs), while `get_kcl_files` returns
/// relative paths. Without normalization the report would carry both
/// spellings and the executable-line back-fill would fail to populate
/// the entry that actually holds the hits.
fn collect_executable_lines(
    normal_files: &[String],
    test_files: &[String],
) -> BTreeMap<String, Vec<u64>> {
    let mut out: BTreeMap<String, Vec<u64>> = BTreeMap::new();
    let all = normal_files.iter().chain(test_files.iter());
    for file in all {
        let module = match parse_file_force_errors(file, None) {
            Ok(m) => m,
            Err(_) => continue,
        };
        let mut lines_set: std::collections::BTreeSet<u64> = std::collections::BTreeSet::new();
        {
            let mut collector = LineCollector::new(&mut lines_set);
            for stmt in &module.body {
                collector.visit_stmt(stmt);
            }
        }
        let mut lines: Vec<u64> = lines_set.into_iter().collect();
        lines.sort_unstable();
        lines.dedup();
        lines.retain(|l| *l != 0);
        if lines.is_empty() {
            continue;
        }
        let key = canonicalize_for_coverage(file);
        eprintln!(
            "executable map key for {file}: {key:?} ({} lines)",
            lines.len()
        );
        out.entry(key).or_insert(lines);
    }
    out
}

/// Recursive AST visitor that records every statement's start line.
/// We only care about `Stmt` nodes — `Expr` coverage is implicit
/// (expressions execute with the surrounding statement).
///
/// This visitor recurses into statement sequences that may contain
/// nested statements: `if` bodies, `if` `orelse`, `schema` bodies,
/// `rule` bodies, and `lambda` bodies (reached via the `Expr::Lambda`
/// in the surrounding statement). Other statement variants
/// (`Assign`, `Expr`, `Assert`, ...) contain only expressions, which
/// are visited by the eager walker alongside their enclosing statement
/// and therefore don't need separate coverage tracking.
struct LineCollector<'a> {
    lines: &'a mut std::collections::BTreeSet<u64>,
}

impl<'a> LineCollector<'a> {
    fn new(lines: &'a mut std::collections::BTreeSet<u64>) -> Self {
        Self { lines }
    }
    fn visit_stmt(&mut self, stmt: &ast::Node<ast::Stmt>) {
        if stmt.line != 0 {
            self.lines.insert(stmt.line);
        }
        match &stmt.node {
            ast::Stmt::If(if_stmt) => {
                for s in &if_stmt.body {
                    self.visit_stmt(s);
                }
                for s in &if_stmt.orelse {
                    self.visit_stmt(s);
                }
            }
            ast::Stmt::Schema(schema) => {
                for m in &schema.body {
                    self.visit_stmt(m);
                }
            }
            ast::Stmt::Assign(assign) => {
                self.visit_lambda_in_expr(&assign.value);
            }
            ast::Stmt::AugAssign(aug) => {
                self.visit_lambda_in_expr(&aug.value);
            }
            ast::Stmt::Expr(expr_stmt) => {
                for e in &expr_stmt.exprs {
                    self.visit_lambda_in_expr(e);
                }
            }
            _ => {}
        }
    }
    /// Walk into expressions looking only for nested `LambdaExpr`
    /// bodies. The other expression shapes (call, list, dict, ...)
    /// cannot contain statements of their own, so visiting them would
    /// only add noise to the line set. Schema attributes are handled
    /// through the top-level `SchemaAttr` variant in `visit_stmt` and
    /// also don't need descent here.
    fn visit_lambda_in_expr(&mut self, expr: &ast::Node<ast::Expr>) {
        if let ast::Expr::Lambda(lam) = &expr.node {
            for s in &lam.body {
                self.visit_stmt(s);
            }
        }
    }
}

/// Normalize a file path for use as a coverage report key. Prefers the
/// canonicalized absolute path so two paths that refer to the same file
/// (`./pkg/lib.k` and `/abs/pkg/lib.k`) collapse onto one key. Falls
/// back to the input string when canonicalization fails (the file may
/// have been deleted between discovery and parse, for example).
fn canonicalize_for_coverage(path: &str) -> String {
    let p = std::path::Path::new(path);
    std::fs::canonicalize(p)
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| path.to_string())
}

/// Load test suite from path
pub fn load_test_suites<P: AsRef<str>>(path: P, opts: &TestOptions) -> Result<Vec<TestSuite>> {
    let pkg_list = get_pkg_list(path.as_ref())?;
    let mut suites = vec![];
    for pkg in &pkg_list {
        let (normal_files, test_files) = get_test_files(pkg)?;
        let mut cases = IndexMap::with_hasher(DefaultHashBuilder::default());
        for file in &test_files {
            let module = parse_file_force_errors(file, None)?;
            for stmt in &module.body {
                if let ast::Stmt::Assign(assign_stmt) = &stmt.node
                    && let ast::Expr::Lambda(_lambda_expr) = &assign_stmt.value.node
                {
                    for target in &assign_stmt.targets {
                        let func_name = target.node.get_name();
                        if is_test_suite(func_name) && should_run(&opts.run_regexp, func_name) {
                            cases.insert(func_name.to_string(), TestCase {});
                        }
                    }
                }
            }
        }
        suites.push(TestSuite {
            pkg: pkg.clone(),
            cases,
            normal_files,
            test_files,
            skip: false,
        });
    }
    Ok(suites)
}

#[inline]
fn get_test_files<P: AsRef<Path>>(pkg: P) -> Result<(Vec<String>, Vec<String>)> {
    let files = get_kcl_files(pkg, false)?;
    let normal_files = files
        .iter()
        .filter(|x| !x.starts_with('_') && !x.ends_with(TEST_FILE_SUFFIX))
        .cloned()
        .collect::<Vec<String>>();
    let test_files = files
        .iter()
        .filter(|x| !x.starts_with('_') && x.ends_with(TEST_FILE_SUFFIX))
        .cloned()
        .collect::<Vec<String>>();
    Ok((normal_files, test_files))
}

#[inline]
fn is_test_suite(name: &str) -> bool {
    name.starts_with(TEST_SUITE_PREFIX)
}

#[inline]
fn should_run(run_regexp: &str, name: &str) -> bool {
    if !run_regexp.is_empty() {
        regex::Regex::new(run_regexp)
            .map(|re| re.is_match(name))
            .unwrap_or_default()
    } else {
        true
    }
}
