data1 = {
    if True:
        key1: "value1"
        key11: 1, key12: True
    elif True:
        key2: "value2"
        key21: 2, key22: True
    elif True:
        key3: "value3"
        key31: 3, key32: True
    else:
        key4: "value4"
        key41: 4, key42: True
}
data2 = {
    if False:
        key1: "value1"
        key11: 1, key12: True
    elif True:
        key2: "value2"
        key21: 2, key22: True
    elif True:
        key3: "value3"
        key31: 3, key32: True
    else:
        key4: "value4"
        key41: 4, key42: True
}
data3 = {
    if False:
        key1: "value1"
        key11: 1, key12: True
    elif False:
        key2: "value2"
        key21: 2, key22: True
    elif True:
        key3: "value3"
        key31: 3, key32: True
    else:
        key4: "value4"
        key41: 4, key42: True
}
data4 = {
    if False:
        key1: "value1"
        key11: 1, key12: True
    elif False:
        key2: "value2"
        key21: 2, key22: True
    elif False:
        key3: "value3"
        key31: 3, key32: True
    else:
        key4: "value4"
        key41: 4, key42: True
}
