// Copyright The KCL Authors. All rights reserved.

// Auto generated by <make gen-api-spec> command, DONOT EDIT!!!

// api-spec:       kcl_context_new
// api-spec(c):    kcl_context_t* kcl_context_new();
// api-spec(llvm): declare %kcl_context_t* @kcl_context_new();

// api-spec:       kcl_context_delete
// api-spec(c):    void kcl_context_delete(kcl_context_t* p);
// api-spec(llvm): declare void @kcl_context_delete(%kcl_context_t* %p);

// api-spec:       kcl_context_set_kcl_location
// api-spec(c):    void kcl_context_set_kcl_location(kcl_context_t* p, char* filename, int32_t line, int32_t col);
// api-spec(llvm): declare void @kcl_context_set_kcl_location(%kcl_context_t* %p, i8* %filename, i32 %line, i32 %col);

// api-spec:       kcl_context_set_kcl_pkgpath
// api-spec(c):    void kcl_context_set_kcl_pkgpath(kcl_context_t* p, char* pkgpath);
// api-spec(llvm): declare void @kcl_context_set_kcl_pkgpath(%kcl_context_t* %p, i8* %pkgpath);

// api-spec:       kcl_context_set_kcl_modpath
// api-spec(c):    void kcl_context_set_kcl_modpath(kcl_context_t* p, char* module_path);
// api-spec(llvm): declare void @kcl_context_set_kcl_modpath(%kcl_context_t* %p, i8* %module_path);

// api-spec:       kcl_context_set_kcl_workdir
// api-spec(c):    void kcl_context_set_kcl_workdir(kcl_context_t* p, char* workdir);
// api-spec(llvm): declare void @kcl_context_set_kcl_workdir(%kcl_context_t* %p, i8* %workdir);

// api-spec:       kcl_context_set_kcl_filename
// api-spec(c):    void kcl_context_set_kcl_filename(kcl_context_t* ctx, char* filename);
// api-spec(llvm): declare void @kcl_context_set_kcl_filename(%kcl_context_t* %ctx, i8* %filename);

// api-spec:       kcl_context_set_kcl_line_col
// api-spec(c):    void kcl_context_set_kcl_line_col(kcl_context_t* ctx, int32_t line, int32_t col);
// api-spec(llvm): declare void @kcl_context_set_kcl_line_col(%kcl_context_t* %ctx, i32 %line, i32 %col);

// api-spec:       kcl_scope_new
// api-spec(c):    kcl_eval_scope_t* kcl_scope_new();
// api-spec(llvm): declare %kcl_eval_scope_t* @kcl_scope_new();

// api-spec:       kcl_scope_delete
// api-spec(c):    void kcl_scope_delete(kcl_eval_scope_t* scope);
// api-spec(llvm): declare void @kcl_scope_delete(%kcl_eval_scope_t* %scope);

// api-spec:       kcl_scope_add_setter
// api-spec(c):    void kcl_scope_add_setter(kcl_context_t* _ctx, kcl_eval_scope_t* scope, char* pkg, char* name, uint64_t* setter);
// api-spec(llvm): declare void @kcl_scope_add_setter(%kcl_context_t* %_ctx, %kcl_eval_scope_t* %scope, i8* %pkg, i8* %name, i64* %setter);

// api-spec:       kcl_scope_set
// api-spec(c):    void kcl_scope_set(kcl_context_t* _ctx, kcl_eval_scope_t* scope, char* pkg, char* name, kcl_value_ref_t* value);
// api-spec(llvm): declare void @kcl_scope_set(%kcl_context_t* %_ctx, %kcl_eval_scope_t* %scope, i8* %pkg, i8* %name, %kcl_value_ref_t* %value);

// api-spec:       kcl_scope_get
// api-spec(c):    kcl_value_ref_t* kcl_scope_get(kcl_context_t* ctx, kcl_eval_scope_t* scope, char* pkg, char* name, char* target, kcl_value_ref_t* default);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_scope_get(%kcl_context_t* %ctx, %kcl_eval_scope_t* %scope, i8* %pkg, i8* %name, i8* %target, %kcl_value_ref_t* %default);

// api-spec:       kcl_context_set_debug_mode
// api-spec(c):    void kcl_context_set_debug_mode(kcl_context_t* p, kcl_bool_t v);
// api-spec(llvm): declare void @kcl_context_set_debug_mode(%kcl_context_t* %p, %kcl_bool_t %v);

// api-spec:       kcl_context_set_strict_range_check
// api-spec(c):    void kcl_context_set_strict_range_check(kcl_context_t* p, kcl_bool_t v);
// api-spec(llvm): declare void @kcl_context_set_strict_range_check(%kcl_context_t* %p, %kcl_bool_t %v);

// api-spec:       kcl_context_set_disable_none
// api-spec(c):    void kcl_context_set_disable_none(kcl_context_t* p, kcl_bool_t v);
// api-spec(llvm): declare void @kcl_context_set_disable_none(%kcl_context_t* %p, %kcl_bool_t %v);

// api-spec:       kcl_context_set_disable_schema_check
// api-spec(c):    void kcl_context_set_disable_schema_check(kcl_context_t* p, kcl_bool_t v);
// api-spec(llvm): declare void @kcl_context_set_disable_schema_check(%kcl_context_t* %p, %kcl_bool_t %v);

// api-spec:       kcl_context_invoke
// api-spec(c):    char* kcl_context_invoke(kcl_context_t* p, char* method, char* args, char* kwargs);
// api-spec(llvm): declare i8* @kcl_context_invoke(%kcl_context_t* %p, i8* %method, i8* %args, i8* %kwargs);

// api-spec:       kcl_context_pkgpath_is_imported
// api-spec(c):    kcl_bool_t kcl_context_pkgpath_is_imported(kcl_context_t* ctx, kcl_char_t* pkgpath);
// api-spec(llvm): declare %kcl_bool_t @kcl_context_pkgpath_is_imported(%kcl_context_t* %ctx, %kcl_char_t* %pkgpath);

// api-spec:       kcl_context_set_import_names
// api-spec(c):    void kcl_context_set_import_names(kcl_context_t* p, kcl_value_ref_t* import_names);
// api-spec(llvm): declare void @kcl_context_set_import_names(%kcl_context_t* %p, %kcl_value_ref_t* %import_names);

// api-spec:       kcl_value_Undefined
// api-spec(c):    kcl_value_ref_t* kcl_value_Undefined(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Undefined(%kcl_context_t* %ctx);

// api-spec:       kcl_value_None
// api-spec(c):    kcl_value_ref_t* kcl_value_None(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_None(%kcl_context_t* %ctx);

// api-spec:       kcl_value_True
// api-spec(c):    kcl_value_ref_t* kcl_value_True(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_True(%kcl_context_t* %ctx);

// api-spec:       kcl_value_False
// api-spec(c):    kcl_value_ref_t* kcl_value_False(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_False(%kcl_context_t* %ctx);

// api-spec:       kcl_value_Bool
// api-spec(c):    kcl_value_ref_t* kcl_value_Bool(kcl_context_t* ctx, kcl_bool_t v);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Bool(%kcl_context_t* %ctx, %kcl_bool_t %v);

// api-spec:       kcl_value_Int
// api-spec(c):    kcl_value_ref_t* kcl_value_Int(kcl_context_t* ctx, kcl_int_t v);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Int(%kcl_context_t* %ctx, %kcl_int_t %v);

// api-spec:       kcl_value_Float
// api-spec(c):    kcl_value_ref_t* kcl_value_Float(kcl_context_t* ctx, kcl_float_t v);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Float(%kcl_context_t* %ctx, %kcl_float_t %v);

// api-spec:       kcl_value_Unit
// api-spec(c):    kcl_value_ref_t* kcl_value_Unit(kcl_context_t* ctx, kcl_float_t v, kcl_int_t raw, kcl_char_t* unit);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Unit(%kcl_context_t* %ctx, %kcl_float_t %v, %kcl_int_t %raw, %kcl_char_t* %unit);

// api-spec:       kcl_value_Str
// api-spec(c):    kcl_value_ref_t* kcl_value_Str(kcl_context_t* ctx, kcl_char_t* v);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Str(%kcl_context_t* %ctx, %kcl_char_t* %v);

// api-spec:       kcl_value_List
// api-spec(c):    kcl_value_ref_t* kcl_value_List(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_List(%kcl_context_t* %ctx);

// api-spec:       kcl_value_List6
// api-spec(c):    kcl_value_ref_t* kcl_value_List6(kcl_context_t* ctx, kcl_value_ref_t* v1, kcl_value_ref_t* v2, kcl_value_ref_t* v3, kcl_value_ref_t* v4, kcl_value_ref_t* v5, kcl_value_ref_t* v6);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_List6(%kcl_context_t* %ctx, %kcl_value_ref_t* %v1, %kcl_value_ref_t* %v2, %kcl_value_ref_t* %v3, %kcl_value_ref_t* %v4, %kcl_value_ref_t* %v5, %kcl_value_ref_t* %v6);

// api-spec:       kcl_value_List10
// api-spec(c):    kcl_value_ref_t* kcl_value_List10(kcl_context_t* ctx, kcl_value_ref_t* v1, kcl_value_ref_t* v2, kcl_value_ref_t* v3, kcl_value_ref_t* v4, kcl_value_ref_t* v5, kcl_value_ref_t* v6, kcl_value_ref_t* v7, kcl_value_ref_t* v8, kcl_value_ref_t* v9, kcl_value_ref_t* v10);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_List10(%kcl_context_t* %ctx, %kcl_value_ref_t* %v1, %kcl_value_ref_t* %v2, %kcl_value_ref_t* %v3, %kcl_value_ref_t* %v4, %kcl_value_ref_t* %v5, %kcl_value_ref_t* %v6, %kcl_value_ref_t* %v7, %kcl_value_ref_t* %v8, %kcl_value_ref_t* %v9, %kcl_value_ref_t* %v10);

// api-spec:       kcl_value_Dict
// api-spec(c):    kcl_value_ref_t* kcl_value_Dict(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Dict(%kcl_context_t* %ctx);

// api-spec:       kcl_value_Schema
// api-spec(c):    kcl_value_ref_t* kcl_value_Schema(kcl_context_t* ctx);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Schema(%kcl_context_t* %ctx);

// api-spec:       kcl_value_schema_with_config
// api-spec(c):    kcl_value_ref_t* kcl_value_schema_with_config(kcl_context_t* ctx, kcl_value_ref_t* schema_dict, kcl_value_ref_t* config, kcl_value_ref_t* config_meta, kcl_char_t* name, kcl_char_t* pkgpath, kcl_value_ref_t* is_sub_schema, kcl_value_ref_t* record_instance, kcl_value_ref_t* instance_pkgpath, kcl_value_ref_t* optional_mapping, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_schema_with_config(%kcl_context_t* %ctx, %kcl_value_ref_t* %schema_dict, %kcl_value_ref_t* %config, %kcl_value_ref_t* %config_meta, %kcl_char_t* %name, %kcl_char_t* %pkgpath, %kcl_value_ref_t* %is_sub_schema, %kcl_value_ref_t* %record_instance, %kcl_value_ref_t* %instance_pkgpath, %kcl_value_ref_t* %optional_mapping, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_value_Function
// api-spec(c):    kcl_value_ref_t* kcl_value_Function(kcl_context_t* ctx, uint64_t* fn_ptr, kcl_value_ref_t* closure, kcl_char_t* name, kcl_bool_t is_external);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Function(%kcl_context_t* %ctx, i64* %fn_ptr, %kcl_value_ref_t* %closure, %kcl_char_t* %name, %kcl_bool_t %is_external);

// api-spec:       kcl_value_Function_using_ptr
// api-spec(c):    kcl_value_ref_t* kcl_value_Function_using_ptr(kcl_context_t* ctx, uint64_t* fn_ptr, kcl_char_t* name);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_Function_using_ptr(%kcl_context_t* %ctx, i64* %fn_ptr, %kcl_char_t* %name);

// api-spec:       kcl_value_schema_function
// api-spec(c):    kcl_value_ref_t* kcl_value_schema_function(kcl_context_t* ctx, uint64_t* fn_ptr, uint64_t* check_fn_ptr, kcl_value_ref_t* attr_map, kcl_char_t* tpe);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_schema_function(%kcl_context_t* %ctx, i64* %fn_ptr, i64* %check_fn_ptr, %kcl_value_ref_t* %attr_map, %kcl_char_t* %tpe);

// api-spec:       kcl_value_from_json
// api-spec(c):    kcl_value_ref_t* kcl_value_from_json(kcl_context_t* ctx, kcl_char_t* s);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_from_json(%kcl_context_t* %ctx, %kcl_char_t* %s);

// api-spec:       kcl_value_to_json_value
// api-spec(c):    kcl_value_ref_t* kcl_value_to_json_value(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_to_json_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_to_json_value_with_null
// api-spec(c):    kcl_value_ref_t* kcl_value_to_json_value_with_null(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_to_json_value_with_null(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_plan_to_json
// api-spec(c):    kcl_value_ref_t* kcl_value_plan_to_json(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_plan_to_json(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_plan_to_yaml
// api-spec(c):    kcl_value_ref_t* kcl_value_plan_to_yaml(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_plan_to_yaml(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_to_yaml_value
// api-spec(c):    kcl_value_ref_t* kcl_value_to_yaml_value(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_to_yaml_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_to_str_value
// api-spec(c):    kcl_value_ref_t* kcl_value_to_str_value(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_to_str_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_Str_ptr
// api-spec(c):    kcl_char_t* kcl_value_Str_ptr(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_char_t* @kcl_value_Str_ptr(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_function_ptr
// api-spec(c):    uint64_t* kcl_value_function_ptr(kcl_value_ref_t* p);
// api-spec(llvm): declare i64* @kcl_value_function_ptr(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_check_function_ptr
// api-spec(c):    uint64_t* kcl_value_check_function_ptr(kcl_value_ref_t* p);
// api-spec(llvm): declare i64* @kcl_value_check_function_ptr(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_function_invoke
// api-spec(c):    kcl_value_ref_t* kcl_value_function_invoke(kcl_value_ref_t* p, kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs, kcl_char_t* pkgpath, kcl_value_ref_t* is_in_schema);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_function_invoke(%kcl_value_ref_t* %p, %kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs, %kcl_char_t* %pkgpath, %kcl_value_ref_t* %is_in_schema);

// api-spec:       kcl_value_deep_copy
// api-spec(c):    kcl_value_ref_t* kcl_value_deep_copy(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_deep_copy(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_value_delete
// api-spec(c):    void kcl_value_delete(kcl_value_ref_t* p);
// api-spec(llvm): declare void @kcl_value_delete(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_iter
// api-spec(c):    kcl_iterator_t* kcl_value_iter(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_iterator_t* @kcl_value_iter(%kcl_value_ref_t* %p);

// api-spec:       kcl_iterator_delete
// api-spec(c):    void kcl_iterator_delete(kcl_iterator_t* p);
// api-spec(llvm): declare void @kcl_iterator_delete(%kcl_iterator_t* %p);

// api-spec:       kcl_iterator_is_end
// api-spec(c):    kcl_bool_t kcl_iterator_is_end(kcl_iterator_t* p);
// api-spec(llvm): declare %kcl_bool_t @kcl_iterator_is_end(%kcl_iterator_t* %p);

// api-spec:       kcl_iterator_cur_key
// api-spec(c):    kcl_value_ref_t* kcl_iterator_cur_key(kcl_iterator_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_iterator_cur_key(%kcl_iterator_t* %p);

// api-spec:       kcl_iterator_cur_value
// api-spec(c):    kcl_value_ref_t* kcl_iterator_cur_value(kcl_iterator_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_iterator_cur_value(%kcl_iterator_t* %p);

// api-spec:       kcl_iterator_next_value
// api-spec(c):    kcl_value_ref_t* kcl_iterator_next_value(kcl_iterator_t* p, kcl_value_ref_t* host);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_iterator_next_value(%kcl_iterator_t* %p, %kcl_value_ref_t* %host);

// api-spec:       kcl_list_len
// api-spec(c):    kcl_size_t kcl_list_len(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_size_t @kcl_list_len(%kcl_value_ref_t* %p);

// api-spec:       kcl_list_resize
// api-spec(c):    void kcl_list_resize(kcl_value_ref_t* p, kcl_size_t newsize);
// api-spec(llvm): declare void @kcl_list_resize(%kcl_value_ref_t* %p, %kcl_size_t %newsize);

// api-spec:       kcl_list_clear
// api-spec(c):    void kcl_list_clear(kcl_value_ref_t* p);
// api-spec(llvm): declare void @kcl_list_clear(%kcl_value_ref_t* %p);

// api-spec:       kcl_list_count
// api-spec(c):    kcl_value_ref_t* kcl_list_count(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* item);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_count(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %item);

// api-spec:       kcl_list_find
// api-spec(c):    kcl_value_ref_t* kcl_list_find(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* item);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_find(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %item);

// api-spec:       kcl_list_insert
// api-spec(c):    void kcl_list_insert(kcl_value_ref_t* p, kcl_value_ref_t* index, kcl_value_ref_t* value);
// api-spec(llvm): declare void @kcl_list_insert(%kcl_value_ref_t* %p, %kcl_value_ref_t* %index, %kcl_value_ref_t* %value);

// api-spec:       kcl_list_get
// api-spec(c):    kcl_value_ref_t* kcl_list_get(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_size_t i);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_get(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_size_t %i);

// api-spec:       kcl_list_get_option
// api-spec(c):    kcl_value_ref_t* kcl_list_get_option(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_size_t i);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_get_option(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_size_t %i);

// api-spec:       kcl_list_set
// api-spec(c):    void kcl_list_set(kcl_value_ref_t* p, kcl_size_t i, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_list_set(%kcl_value_ref_t* %p, %kcl_size_t %i, %kcl_value_ref_t* %v);

// api-spec:       kcl_list_pop
// api-spec(c):    kcl_value_ref_t* kcl_list_pop(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_pop(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_list_pop_first
// api-spec(c):    kcl_value_ref_t* kcl_list_pop_first(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_list_pop_first(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_list_append
// api-spec(c):    void kcl_list_append(kcl_value_ref_t* p, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_list_append(%kcl_value_ref_t* %p, %kcl_value_ref_t* %v);

// api-spec:       kcl_list_append_bool
// api-spec(c):    void kcl_list_append_bool(kcl_value_ref_t* p, kcl_bool_t v);
// api-spec(llvm): declare void @kcl_list_append_bool(%kcl_value_ref_t* %p, %kcl_bool_t %v);

// api-spec:       kcl_list_append_int
// api-spec(c):    void kcl_list_append_int(kcl_value_ref_t* p, kcl_int_t v);
// api-spec(llvm): declare void @kcl_list_append_int(%kcl_value_ref_t* %p, %kcl_int_t %v);

// api-spec:       kcl_list_append_float
// api-spec(c):    void kcl_list_append_float(kcl_value_ref_t* p, kcl_float_t v);
// api-spec(llvm): declare void @kcl_list_append_float(%kcl_value_ref_t* %p, %kcl_float_t %v);

// api-spec:       kcl_list_append_str
// api-spec(c):    void kcl_list_append_str(kcl_value_ref_t* p, kcl_char_t* v);
// api-spec(llvm): declare void @kcl_list_append_str(%kcl_value_ref_t* %p, %kcl_char_t* %v);

// api-spec:       kcl_list_append_unpack
// api-spec(c):    void kcl_list_append_unpack(kcl_value_ref_t* p, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_list_append_unpack(%kcl_value_ref_t* %p, %kcl_value_ref_t* %v);

// api-spec:       kcl_list_remove_at
// api-spec(c):    void kcl_list_remove_at(kcl_value_ref_t* p, kcl_size_t i);
// api-spec(llvm): declare void @kcl_list_remove_at(%kcl_value_ref_t* %p, %kcl_size_t %i);

// api-spec:       kcl_dict_len
// api-spec(c):    kcl_size_t kcl_dict_len(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_size_t @kcl_dict_len(%kcl_value_ref_t* %p);

// api-spec:       kcl_dict_clear
// api-spec(c):    void kcl_dict_clear(kcl_value_ref_t* p);
// api-spec(llvm): declare void @kcl_dict_clear(%kcl_value_ref_t* %p);

// api-spec:       kcl_dict_is_override_attr
// api-spec(c):    kcl_bool_t kcl_dict_is_override_attr(kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare %kcl_bool_t @kcl_dict_is_override_attr(%kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_dict_get
// api-spec(c):    kcl_value_ref_t* kcl_dict_get(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* key);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_get(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %key);

// api-spec:       kcl_dict_has_value
// api-spec(c):    kcl_bool_t kcl_dict_has_value(kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare %kcl_bool_t @kcl_dict_has_value(%kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_dict_get_value
// api-spec(c):    kcl_value_ref_t* kcl_dict_get_value(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_get_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_dict_get_entry
// api-spec(c):    kcl_value_ref_t* kcl_dict_get_entry(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_get_entry(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_dict_get_value_by_path
// api-spec(c):    kcl_value_ref_t* kcl_dict_get_value_by_path(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* path);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_get_value_by_path(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %path);

// api-spec:       kcl_dict_set_value
// api-spec(c):    void kcl_dict_set_value(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* val);
// api-spec(llvm): declare void @kcl_dict_set_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %val);

// api-spec:       kcl_dict_keys
// api-spec(c):    kcl_value_ref_t* kcl_dict_keys(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_keys(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_dict_values
// api-spec(c):    kcl_value_ref_t* kcl_dict_values(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_dict_values(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_dict_insert
// api-spec(c):    void kcl_dict_insert(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* v, kcl_size_t op, kcl_size_t insert_index, kcl_bool_t has_insert_index);
// api-spec(llvm): declare void @kcl_dict_insert(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %v, %kcl_size_t %op, %kcl_size_t %insert_index, %kcl_bool_t %has_insert_index);

// api-spec:       kcl_dict_merge
// api-spec(c):    void kcl_dict_merge(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* v, kcl_size_t op, kcl_size_t insert_index, kcl_bool_t has_insert_index);
// api-spec(llvm): declare void @kcl_dict_merge(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %v, %kcl_size_t %op, %kcl_size_t %insert_index, %kcl_bool_t %has_insert_index);

// api-spec:       kcl_dict_insert_value
// api-spec(c):    void kcl_dict_insert_value(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* key, kcl_value_ref_t* v, kcl_size_t op, kcl_size_t insert_index, kcl_bool_t has_insert_index);
// api-spec(llvm): declare void @kcl_dict_insert_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %key, %kcl_value_ref_t* %v, %kcl_size_t %op, %kcl_size_t %insert_index, %kcl_bool_t %has_insert_index);

// api-spec:       kcl_dict_update_key_value
// api-spec(c):    void kcl_dict_update_key_value(kcl_value_ref_t* p, kcl_value_ref_t* key, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_dict_update_key_value(%kcl_value_ref_t* %p, %kcl_value_ref_t* %key, %kcl_value_ref_t* %v);

// api-spec:       kcl_dict_safe_insert
// api-spec(c):    void kcl_dict_safe_insert(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* v, kcl_size_t op, kcl_size_t insert_index, kcl_bool_t has_insert_index);
// api-spec(llvm): declare void @kcl_dict_safe_insert(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %v, %kcl_size_t %op, %kcl_size_t %insert_index, %kcl_bool_t %has_insert_index);

// api-spec:       kcl_dict_insert_unpack
// api-spec(c):    void kcl_dict_insert_unpack(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_dict_insert_unpack(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %v);

// api-spec:       kcl_default_collection_insert_int_pointer
// api-spec(c):    void kcl_default_collection_insert_int_pointer(kcl_value_ref_t* p, kcl_char_t* key, uint64_t* ptr);
// api-spec(llvm): declare void @kcl_default_collection_insert_int_pointer(%kcl_value_ref_t* %p, %kcl_char_t* %key, i64* %ptr);

// api-spec:       kcl_default_collection_insert_value
// api-spec(c):    void kcl_default_collection_insert_value(kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* value);
// api-spec(llvm): declare void @kcl_default_collection_insert_value(%kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %value);

// api-spec:       kcl_dict_remove
// api-spec(c):    void kcl_dict_remove(kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare void @kcl_dict_remove(%kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_dict_update
// api-spec(c):    void kcl_dict_update(kcl_value_ref_t* p, kcl_value_ref_t* v);
// api-spec(llvm): declare void @kcl_dict_update(%kcl_value_ref_t* %p, %kcl_value_ref_t* %v);

// api-spec:       kcl_value_is_truthy
// api-spec(c):    kcl_bool_t kcl_value_is_truthy(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_bool_t @kcl_value_is_truthy(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_len
// api-spec(c):    kcl_size_t kcl_value_len(kcl_value_ref_t* p);
// api-spec(llvm): declare %kcl_size_t @kcl_value_len(%kcl_value_ref_t* %p);

// api-spec:       kcl_value_cmp_equal_to
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_equal_to(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_equal_to(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_cmp_not_equal_to
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_not_equal_to(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_not_equal_to(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_cmp_less_than
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_less_than(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_less_than(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_cmp_less_than_or_equal
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_less_than_or_equal(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_less_than_or_equal(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_cmp_greater_than
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_greater_than(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_greater_than(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_cmp_greater_than_or_equal
// api-spec(c):    kcl_value_ref_t* kcl_value_cmp_greater_than_or_equal(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_cmp_greater_than_or_equal(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_is
// api-spec(c):    kcl_value_ref_t* kcl_value_is(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_is(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_is_not
// api-spec(c):    kcl_value_ref_t* kcl_value_is_not(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_is_not(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_in
// api-spec(c):    kcl_value_ref_t* kcl_value_in(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_in(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_not_in
// api-spec(c):    kcl_value_ref_t* kcl_value_not_in(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_not_in(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_as
// api-spec(c):    kcl_value_ref_t* kcl_value_as(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_as(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_unary_plus
// api-spec(c):    kcl_value_ref_t* kcl_value_unary_plus(kcl_context_t* ctx, kcl_value_ref_t* a);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_unary_plus(%kcl_context_t* %ctx, %kcl_value_ref_t* %a);

// api-spec:       kcl_value_unary_minus
// api-spec(c):    kcl_value_ref_t* kcl_value_unary_minus(kcl_context_t* ctx, kcl_value_ref_t* a);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_unary_minus(%kcl_context_t* %ctx, %kcl_value_ref_t* %a);

// api-spec:       kcl_value_unary_not
// api-spec(c):    kcl_value_ref_t* kcl_value_unary_not(kcl_context_t* ctx, kcl_value_ref_t* a);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_unary_not(%kcl_context_t* %ctx, %kcl_value_ref_t* %a);

// api-spec:       kcl_value_unary_l_not
// api-spec(c):    kcl_value_ref_t* kcl_value_unary_l_not(kcl_context_t* ctx, kcl_value_ref_t* a);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_unary_l_not(%kcl_context_t* %ctx, %kcl_value_ref_t* %a);

// api-spec:       kcl_value_op_add
// api-spec(c):    kcl_value_ref_t* kcl_value_op_add(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_add(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_sub
// api-spec(c):    kcl_value_ref_t* kcl_value_op_sub(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_sub(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_mul
// api-spec(c):    kcl_value_ref_t* kcl_value_op_mul(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_mul(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_div
// api-spec(c):    kcl_value_ref_t* kcl_value_op_div(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_div(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_mod
// api-spec(c):    kcl_value_ref_t* kcl_value_op_mod(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_mod(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_pow
// api-spec(c):    kcl_value_ref_t* kcl_value_op_pow(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_pow(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_floor_div
// api-spec(c):    kcl_value_ref_t* kcl_value_op_floor_div(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_floor_div(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_bit_lshift
// api-spec(c):    kcl_value_ref_t* kcl_value_op_bit_lshift(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_bit_lshift(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_bit_rshift
// api-spec(c):    kcl_value_ref_t* kcl_value_op_bit_rshift(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_bit_rshift(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_bit_and
// api-spec(c):    kcl_value_ref_t* kcl_value_op_bit_and(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_bit_and(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_bit_xor
// api-spec(c):    kcl_value_ref_t* kcl_value_op_bit_xor(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_bit_xor(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_bit_or
// api-spec(c):    kcl_value_ref_t* kcl_value_op_bit_or(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_bit_or(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_add
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_add(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_add(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_sub
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_sub(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_sub(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_mul
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_mul(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_mul(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_div
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_div(kcl_context_t* _ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_div(%kcl_context_t* %_ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_mod
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_mod(kcl_context_t* _ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_mod(%kcl_context_t* %_ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_pow
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_pow(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_pow(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_floor_div
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_floor_div(kcl_context_t* _ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_floor_div(%kcl_context_t* %_ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_bit_lshift
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_bit_lshift(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_bit_lshift(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_bit_rshift
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_bit_rshift(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_bit_rshift(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_bit_and
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_bit_and(kcl_context_t* _ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_bit_and(%kcl_context_t* %_ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_bit_xor
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_bit_xor(kcl_context_t* _ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_bit_xor(%kcl_context_t* %_ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_op_aug_bit_or
// api-spec(c):    kcl_value_ref_t* kcl_value_op_aug_bit_or(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_op_aug_bit_or(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_union
// api-spec(c):    kcl_value_ref_t* kcl_value_union(kcl_context_t* ctx, kcl_value_ref_t* schema, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_union(%kcl_context_t* %ctx, %kcl_value_ref_t* %schema, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_logic_and
// api-spec(c):    kcl_value_ref_t* kcl_value_logic_and(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_logic_and(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_logic_or
// api-spec(c):    kcl_value_ref_t* kcl_value_logic_or(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_logic_or(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_subscr
// api-spec(c):    kcl_value_ref_t* kcl_value_subscr(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_subscr(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_subscr_set
// api-spec(c):    void kcl_value_subscr_set(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_value_ref_t* index, kcl_value_ref_t* val);
// api-spec(llvm): declare void @kcl_value_subscr_set(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_value_ref_t* %index, %kcl_value_ref_t* %val);

// api-spec:       kcl_value_subscr_option
// api-spec(c):    kcl_value_ref_t* kcl_value_subscr_option(kcl_context_t* ctx, kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_subscr_option(%kcl_context_t* %ctx, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_load_attr
// api-spec(c):    kcl_value_ref_t* kcl_value_load_attr(kcl_context_t* ctx, kcl_value_ref_t* obj, kcl_char_t* key);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_load_attr(%kcl_context_t* %ctx, %kcl_value_ref_t* %obj, %kcl_char_t* %key);

// api-spec:       kcl_value_load_attr_option
// api-spec(c):    kcl_value_ref_t* kcl_value_load_attr_option(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_load_attr_option(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key);

// api-spec:       kcl_value_remove_item
// api-spec(c):    void kcl_value_remove_item(kcl_value_ref_t* a, kcl_value_ref_t* b);
// api-spec(llvm): declare void @kcl_value_remove_item(%kcl_value_ref_t* %a, %kcl_value_ref_t* %b);

// api-spec:       kcl_value_slice
// api-spec(c):    kcl_value_ref_t* kcl_value_slice(kcl_context_t* ctx, kcl_value_ref_t* x, kcl_value_ref_t* a, kcl_value_ref_t* b, kcl_value_ref_t* step);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_slice(%kcl_context_t* %ctx, %kcl_value_ref_t* %x, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b, %kcl_value_ref_t* %step);

// api-spec:       kcl_value_slice_option
// api-spec(c):    kcl_value_ref_t* kcl_value_slice_option(kcl_context_t* ctx, kcl_value_ref_t* x, kcl_value_ref_t* a, kcl_value_ref_t* b, kcl_value_ref_t* step);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_slice_option(%kcl_context_t* %ctx, %kcl_value_ref_t* %x, %kcl_value_ref_t* %a, %kcl_value_ref_t* %b, %kcl_value_ref_t* %step);

// api-spec:       kcl_schema_backtrack_cache
// api-spec(c):    void kcl_schema_backtrack_cache(kcl_context_t* ctx, kcl_value_ref_t* schema, kcl_value_ref_t* cache, kcl_value_ref_t* cal_map, kcl_char_t* name, kcl_value_ref_t* runtime_type);
// api-spec(llvm): declare void @kcl_schema_backtrack_cache(%kcl_context_t* %ctx, %kcl_value_ref_t* %schema, %kcl_value_ref_t* %cache, %kcl_value_ref_t* %cal_map, %kcl_char_t* %name, %kcl_value_ref_t* %runtime_type);

// api-spec:       kcl_schema_instances
// api-spec(c):    kcl_value_ref_t* kcl_schema_instances(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_schema_instances(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_schema_value_check
// api-spec(c):    void kcl_schema_value_check(kcl_context_t* ctx, kcl_value_ref_t* schema_value, kcl_value_ref_t* schema_config, kcl_value_ref_t* _config_meta, kcl_char_t* schema_name, kcl_value_ref_t* index_sign_value, kcl_char_t* key_name, kcl_char_t* key_type, kcl_char_t* value_type, kcl_bool_t _any_other);
// api-spec(llvm): declare void @kcl_schema_value_check(%kcl_context_t* %ctx, %kcl_value_ref_t* %schema_value, %kcl_value_ref_t* %schema_config, %kcl_value_ref_t* %_config_meta, %kcl_char_t* %schema_name, %kcl_value_ref_t* %index_sign_value, %kcl_char_t* %key_name, %kcl_char_t* %key_type, %kcl_char_t* %value_type, %kcl_bool_t %_any_other);

// api-spec:       kcl_schema_do_check_with_index_sign_attr
// api-spec(c):    void kcl_schema_do_check_with_index_sign_attr(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs, uint64_t* check_fn_ptr, kcl_char_t* attr_name);
// api-spec(llvm): declare void @kcl_schema_do_check_with_index_sign_attr(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs, i64* %check_fn_ptr, %kcl_char_t* %attr_name);

// api-spec:       kcl_schema_optional_check
// api-spec(c):    void kcl_schema_optional_check(kcl_context_t* ctx, kcl_value_ref_t* p);
// api-spec(llvm): declare void @kcl_schema_optional_check(%kcl_context_t* %ctx, %kcl_value_ref_t* %p);

// api-spec:       kcl_schema_default_settings
// api-spec(c):    void kcl_schema_default_settings(kcl_value_ref_t* schema_value, kcl_value_ref_t* _config_value, kcl_value_ref_t* args, kcl_value_ref_t* kwargs, kcl_char_t* runtime_type);
// api-spec(llvm): declare void @kcl_schema_default_settings(%kcl_value_ref_t* %schema_value, %kcl_value_ref_t* %_config_value, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs, %kcl_char_t* %runtime_type);

// api-spec:       kcl_schema_assert
// api-spec(c):    void kcl_schema_assert(kcl_context_t* ctx, kcl_value_ref_t* value, kcl_value_ref_t* msg, kcl_value_ref_t* config_meta);
// api-spec(llvm): declare void @kcl_schema_assert(%kcl_context_t* %ctx, %kcl_value_ref_t* %value, %kcl_value_ref_t* %msg, %kcl_value_ref_t* %config_meta);

// api-spec:       kcl_schema_value_new
// api-spec(c):    kcl_value_ref_t* kcl_schema_value_new(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs, kcl_value_ref_t* schema_value_or_func, kcl_value_ref_t* config, kcl_value_ref_t* config_meta, kcl_char_t* pkgpath);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_schema_value_new(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs, %kcl_value_ref_t* %schema_value_or_func, %kcl_value_ref_t* %config, %kcl_value_ref_t* %config_meta, %kcl_char_t* %pkgpath);

// api-spec:       kcl_convert_collection_value
// api-spec(c):    kcl_value_ref_t* kcl_convert_collection_value(kcl_context_t* ctx, kcl_value_ref_t* value, kcl_char_t* tpe, kcl_value_ref_t* is_in_schema);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_convert_collection_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %value, %kcl_char_t* %tpe, %kcl_value_ref_t* %is_in_schema);

// api-spec:       kcl_schema_get_value
// api-spec(c):    kcl_value_ref_t* kcl_schema_get_value(kcl_context_t* ctx, kcl_value_ref_t* p, kcl_char_t* key, kcl_value_ref_t* config, kcl_value_ref_t* config_meta, kcl_value_ref_t* cal_map, kcl_char_t* target_attr, kcl_value_ref_t* backtrack_level_map, kcl_value_ref_t* backtrack_cache, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_schema_get_value(%kcl_context_t* %ctx, %kcl_value_ref_t* %p, %kcl_char_t* %key, %kcl_value_ref_t* %config, %kcl_value_ref_t* %config_meta, %kcl_value_ref_t* %cal_map, %kcl_char_t* %target_attr, %kcl_value_ref_t* %backtrack_level_map, %kcl_value_ref_t* %backtrack_cache, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_config_attr_map
// api-spec(c):    void kcl_config_attr_map(kcl_value_ref_t* value, kcl_char_t* name, kcl_char_t* type_str);
// api-spec(llvm): declare void @kcl_config_attr_map(%kcl_value_ref_t* %value, %kcl_char_t* %name, %kcl_char_t* %type_str);

// api-spec:       kcl_value_Decorator
// api-spec(c):    kcl_decorator_value_t* kcl_value_Decorator(kcl_context_t* ctx, kcl_char_t* name, kcl_value_ref_t* args, kcl_value_ref_t* kwargs, kcl_value_ref_t* config_meta, kcl_char_t* attr_name, kcl_value_ref_t* config_value, kcl_value_ref_t* is_schema_target);
// api-spec(llvm): declare %kcl_decorator_value_t* @kcl_value_Decorator(%kcl_context_t* %ctx, %kcl_char_t* %name, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs, %kcl_value_ref_t* %config_meta, %kcl_char_t* %attr_name, %kcl_value_ref_t* %config_value, %kcl_value_ref_t* %is_schema_target);

// api-spec:       kcl_builtin_str_lower
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_lower(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_lower(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_upper
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_upper(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_upper(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_capitalize
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_capitalize(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_capitalize(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_chars
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_chars(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_chars(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_count
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_count(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_count(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_endswith
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_endswith(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_endswith(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_find
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_find(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_find(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_format
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_format(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_format(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_str_index
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_index(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_index(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_isalnum
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_isalnum(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_isalnum(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_isalpha
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_isalpha(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_isalpha(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_isdigit
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_isdigit(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_isdigit(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_islower
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_islower(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_islower(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_isspace
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_isspace(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_isspace(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_istitle
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_istitle(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_istitle(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_isupper
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_isupper(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_isupper(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_join
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_join(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_join(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_lstrip
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_lstrip(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_lstrip(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_rstrip
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_rstrip(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_rstrip(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_replace
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_replace(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_replace(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_removeprefix
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_removeprefix(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_removeprefix(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_removesuffix
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_removesuffix(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_removesuffix(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_rfind
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_rfind(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_rfind(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_rindex
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_rindex(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_rindex(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_rsplit
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_rsplit(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_rsplit(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_str_split
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_split(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_split(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_str_splitlines
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_splitlines(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_splitlines(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_str_startswith
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_startswith(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_startswith(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_strip
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_strip(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_strip(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_str_title
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str_title(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str_title(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_base32_encode
// api-spec(c):    kcl_value_ref_t* kcl_base32_encode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_base32_encode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_base32_decode
// api-spec(c):    kcl_value_ref_t* kcl_base32_decode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_base32_decode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_base64_encode
// api-spec(c):    kcl_value_ref_t* kcl_base64_encode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_base64_encode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_base64_decode
// api-spec(c):    kcl_value_ref_t* kcl_base64_decode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_base64_decode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_value_union_all
// api-spec(c):    kcl_value_ref_t* kcl_value_union_all(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_value_union_all(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_crypto_md5
// api-spec(c):    kcl_value_ref_t* kcl_crypto_md5(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_md5(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_sha1
// api-spec(c):    kcl_value_ref_t* kcl_crypto_sha1(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_sha1(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_sha224
// api-spec(c):    kcl_value_ref_t* kcl_crypto_sha224(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_sha224(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_sha256
// api-spec(c):    kcl_value_ref_t* kcl_crypto_sha256(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_sha256(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_sha384
// api-spec(c):    kcl_value_ref_t* kcl_crypto_sha384(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_sha384(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_sha512
// api-spec(c):    kcl_value_ref_t* kcl_crypto_sha512(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_sha512(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_blake3
// api-spec(c):    kcl_value_ref_t* kcl_crypto_blake3(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_blake3(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_uuid
// api-spec(c):    kcl_value_ref_t* kcl_crypto_uuid(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_uuid(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_crypto_filesha256
// api-spec(c):    kcl_value_ref_t* kcl_crypto_filesha256(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_filesha256(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_filesha512
// api-spec(c):    kcl_value_ref_t* kcl_crypto_filesha512(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_filesha512(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_crypto_fileblake3
// api-spec(c):    kcl_value_ref_t* kcl_crypto_fileblake3(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_crypto_fileblake3(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_datetime_today
// api-spec(c):    kcl_value_ref_t* kcl_datetime_today(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_datetime_today(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_datetime_now
// api-spec(c):    kcl_value_ref_t* kcl_datetime_now(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_datetime_now(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_datetime_ticks
// api-spec(c):    kcl_value_ref_t* kcl_datetime_ticks(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_datetime_ticks(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_datetime_date
// api-spec(c):    kcl_value_ref_t* kcl_datetime_date(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_datetime_date(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_datetime_validate
// api-spec(c):    kcl_value_ref_t* kcl_datetime_validate(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_datetime_validate(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_json_encode
// api-spec(c):    kcl_value_ref_t* kcl_json_encode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_json_encode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_json_decode
// api-spec(c):    kcl_value_ref_t* kcl_json_decode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_json_decode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_json_validate
// api-spec(c):    kcl_value_ref_t* kcl_json_validate(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_json_validate(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_json_dump_to_file
// api-spec(c):    kcl_value_ref_t* kcl_json_dump_to_file(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_json_dump_to_file(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_manifests_yaml_stream
// api-spec(c):    kcl_value_ref_t* kcl_manifests_yaml_stream(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_manifests_yaml_stream(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_ceil
// api-spec(c):    kcl_value_ref_t* kcl_math_ceil(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_ceil(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_factorial
// api-spec(c):    kcl_value_ref_t* kcl_math_factorial(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_factorial(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_floor
// api-spec(c):    kcl_value_ref_t* kcl_math_floor(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_floor(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_gcd
// api-spec(c):    kcl_value_ref_t* kcl_math_gcd(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_gcd(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_isfinite
// api-spec(c):    kcl_value_ref_t* kcl_math_isfinite(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_isfinite(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_isinf
// api-spec(c):    kcl_value_ref_t* kcl_math_isinf(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_isinf(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_isnan
// api-spec(c):    kcl_value_ref_t* kcl_math_isnan(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_isnan(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_modf
// api-spec(c):    kcl_value_ref_t* kcl_math_modf(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_modf(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_exp
// api-spec(c):    kcl_value_ref_t* kcl_math_exp(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_exp(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_expm1
// api-spec(c):    kcl_value_ref_t* kcl_math_expm1(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_expm1(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_log
// api-spec(c):    kcl_value_ref_t* kcl_math_log(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_log(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_log1p
// api-spec(c):    kcl_value_ref_t* kcl_math_log1p(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_log1p(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_log2
// api-spec(c):    kcl_value_ref_t* kcl_math_log2(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_log2(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_log10
// api-spec(c):    kcl_value_ref_t* kcl_math_log10(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_log10(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_pow
// api-spec(c):    kcl_value_ref_t* kcl_math_pow(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_pow(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_math_sqrt
// api-spec(c):    kcl_value_ref_t* kcl_math_sqrt(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_math_sqrt(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_split_host_port
// api-spec(c):    kcl_value_ref_t* kcl_net_split_host_port(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_split_host_port(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_join_host_port
// api-spec(c):    kcl_value_ref_t* kcl_net_join_host_port(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_join_host_port(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_fqdn
// api-spec(c):    kcl_value_ref_t* kcl_net_fqdn(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_fqdn(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_parse_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_parse_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_parse_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_to_IP4
// api-spec(c):    kcl_value_ref_t* kcl_net_to_IP4(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_to_IP4(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_to_IP6
// api-spec(c):    kcl_value_ref_t* kcl_net_to_IP6(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_to_IP6(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_IP_string
// api-spec(c):    kcl_value_ref_t* kcl_net_IP_string(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_IP_string(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_IPv4
// api-spec(c):    kcl_value_ref_t* kcl_net_is_IPv4(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_IPv4(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_loopback_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_loopback_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_loopback_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_multicast_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_multicast_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_multicast_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_interface_local_multicast_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_interface_local_multicast_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_interface_local_multicast_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_link_local_multicast_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_link_local_multicast_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_link_local_multicast_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_link_local_unicast_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_link_local_unicast_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_link_local_unicast_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_global_unicast_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_global_unicast_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_global_unicast_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_parse_CIDR
// api-spec(c):    kcl_value_ref_t* kcl_net_parse_CIDR(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_parse_CIDR(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_IP_in_CIDR
// api-spec(c):    kcl_value_ref_t* kcl_net_is_IP_in_CIDR(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_IP_in_CIDR(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_is_unspecified_IP
// api-spec(c):    kcl_value_ref_t* kcl_net_is_unspecified_IP(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_is_unspecified_IP(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_CIDR_subnet
// api-spec(c):    kcl_value_ref_t* kcl_net_CIDR_subnet(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_CIDR_subnet(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_CIDR_subnets
// api-spec(c):    kcl_value_ref_t* kcl_net_CIDR_subnets(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_CIDR_subnets(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_CIDR_host
// api-spec(c):    kcl_value_ref_t* kcl_net_CIDR_host(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_CIDR_host(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_net_CIDR_netmask
// api-spec(c):    kcl_value_ref_t* kcl_net_CIDR_netmask(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_net_CIDR_netmask(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_match
// api-spec(c):    kcl_value_ref_t* kcl_regex_match(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_match(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_replace
// api-spec(c):    kcl_value_ref_t* kcl_regex_replace(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_replace(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_compile
// api-spec(c):    kcl_value_ref_t* kcl_regex_compile(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_compile(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_findall
// api-spec(c):    kcl_value_ref_t* kcl_regex_findall(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_findall(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_search
// api-spec(c):    kcl_value_ref_t* kcl_regex_search(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_search(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_regex_split
// api-spec(c):    kcl_value_ref_t* kcl_regex_split(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_regex_split(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_assert
// api-spec(c):    void kcl_assert(kcl_context_t* ctx, kcl_value_ref_t* value, kcl_value_ref_t* msg);
// api-spec(llvm): declare void @kcl_assert(%kcl_context_t* %ctx, %kcl_value_ref_t* %value, %kcl_value_ref_t* %msg);

// api-spec:       kcl_builtin_option_init
// api-spec(c):    void kcl_builtin_option_init(kcl_context_t* ctx, char* key, char* value);
// api-spec(llvm): declare void @kcl_builtin_option_init(%kcl_context_t* %ctx, i8* %key, i8* %value);

// api-spec:       kcl_builtin_option_reset
// api-spec(c):    kcl_value_ref_t* kcl_builtin_option_reset(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_option_reset(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_option
// api-spec(c):    kcl_value_ref_t* kcl_builtin_option(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_option(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_print
// api-spec(c):    kcl_value_ref_t* kcl_builtin_print(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_print(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_len
// api-spec(c):    kcl_value_ref_t* kcl_builtin_len(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_len(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_any_true
// api-spec(c):    kcl_value_ref_t* kcl_builtin_any_true(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_any_true(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_isunique
// api-spec(c):    kcl_value_ref_t* kcl_builtin_isunique(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_isunique(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_sorted
// api-spec(c):    kcl_value_ref_t* kcl_builtin_sorted(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_sorted(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_int
// api-spec(c):    kcl_value_ref_t* kcl_builtin_int(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_int(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_float
// api-spec(c):    kcl_value_ref_t* kcl_builtin_float(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_float(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_bool
// api-spec(c):    kcl_value_ref_t* kcl_builtin_bool(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_bool(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_str
// api-spec(c):    kcl_value_ref_t* kcl_builtin_str(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_str(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_max
// api-spec(c):    kcl_value_ref_t* kcl_builtin_max(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_max(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_min
// api-spec(c):    kcl_value_ref_t* kcl_builtin_min(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_min(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_multiplyof
// api-spec(c):    kcl_value_ref_t* kcl_builtin_multiplyof(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_multiplyof(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_abs
// api-spec(c):    kcl_value_ref_t* kcl_builtin_abs(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_abs(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_all_true
// api-spec(c):    kcl_value_ref_t* kcl_builtin_all_true(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_all_true(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_hex
// api-spec(c):    kcl_value_ref_t* kcl_builtin_hex(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_hex(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_sum
// api-spec(c):    kcl_value_ref_t* kcl_builtin_sum(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_sum(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_pow
// api-spec(c):    kcl_value_ref_t* kcl_builtin_pow(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_pow(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_round
// api-spec(c):    kcl_value_ref_t* kcl_builtin_round(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_round(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_zip
// api-spec(c):    kcl_value_ref_t* kcl_builtin_zip(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_zip(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_builtin_list
// api-spec(c):    kcl_value_ref_t* kcl_builtin_list(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_list(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_dict
// api-spec(c):    kcl_value_ref_t* kcl_builtin_dict(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_dict(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_typeof
// api-spec(c):    kcl_value_ref_t* kcl_builtin_typeof(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_typeof(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_bin
// api-spec(c):    kcl_value_ref_t* kcl_builtin_bin(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_bin(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_oct
// api-spec(c):    kcl_value_ref_t* kcl_builtin_oct(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_oct(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_ord
// api-spec(c):    kcl_value_ref_t* kcl_builtin_ord(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_ord(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_range
// api-spec(c):    kcl_value_ref_t* kcl_builtin_range(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_range(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_builtin_isnullish
// api-spec(c):    kcl_value_ref_t* kcl_builtin_isnullish(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_builtin_isnullish(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_plugin_init
// api-spec(c):    void kcl_plugin_init(void* fn_ptr);
// api-spec(llvm): declare void @kcl_plugin_init(i8* %fn_ptr);

// api-spec:       kcl_plugin_invoke
// api-spec(c):    kcl_value_ref_t* kcl_plugin_invoke(kcl_context_t* ctx, char* method, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_plugin_invoke(%kcl_context_t* %ctx, i8* %method, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_plugin_invoke_json
// api-spec(c):    char* kcl_plugin_invoke_json(char* method, char* args, char* kwargs);
// api-spec(llvm): declare i8* @kcl_plugin_invoke_json(i8* %method, i8* %args, i8* %kwargs);

// api-spec:       kcl_units_to_n
// api-spec(c):    kcl_value_ref_t* kcl_units_to_n(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_n(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_u
// api-spec(c):    kcl_value_ref_t* kcl_units_to_u(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_u(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_m
// api-spec(c):    kcl_value_ref_t* kcl_units_to_m(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_m(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_K
// api-spec(c):    kcl_value_ref_t* kcl_units_to_K(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_K(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_M
// api-spec(c):    kcl_value_ref_t* kcl_units_to_M(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_M(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_G
// api-spec(c):    kcl_value_ref_t* kcl_units_to_G(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_G(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_T
// api-spec(c):    kcl_value_ref_t* kcl_units_to_T(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_T(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_P
// api-spec(c):    kcl_value_ref_t* kcl_units_to_P(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_P(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_Ki
// api-spec(c):    kcl_value_ref_t* kcl_units_to_Ki(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_Ki(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_Mi
// api-spec(c):    kcl_value_ref_t* kcl_units_to_Mi(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_Mi(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_Gi
// api-spec(c):    kcl_value_ref_t* kcl_units_to_Gi(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_Gi(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_Ti
// api-spec(c):    kcl_value_ref_t* kcl_units_to_Ti(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_Ti(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_units_to_Pi
// api-spec(c):    kcl_value_ref_t* kcl_units_to_Pi(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_units_to_Pi(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_encode
// api-spec(c):    kcl_value_ref_t* kcl_yaml_encode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_encode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_encode_all
// api-spec(c):    kcl_value_ref_t* kcl_yaml_encode_all(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_encode_all(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_decode
// api-spec(c):    kcl_value_ref_t* kcl_yaml_decode(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_decode(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_decode_all
// api-spec(c):    kcl_value_ref_t* kcl_yaml_decode_all(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_decode_all(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_dump_to_file
// api-spec(c):    kcl_value_ref_t* kcl_yaml_dump_to_file(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_dump_to_file(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_dump_all_to_file
// api-spec(c):    kcl_value_ref_t* kcl_yaml_dump_all_to_file(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_dump_all_to_file(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_yaml_validate
// api-spec(c):    kcl_value_ref_t* kcl_yaml_validate(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_yaml_validate(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_read
// api-spec(c):    kcl_value_ref_t* kcl_file_read(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_read(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_glob
// api-spec(c):    kcl_value_ref_t* kcl_file_glob(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_glob(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_modpath
// api-spec(c):    kcl_value_ref_t* kcl_file_modpath(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_modpath(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_file_workdir
// api-spec(c):    kcl_value_ref_t* kcl_file_workdir(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_workdir(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_file_current
// api-spec(c):    kcl_value_ref_t* kcl_file_current(kcl_context_t* ctx, kcl_value_ref_t* _args, kcl_value_ref_t* _kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_current(%kcl_context_t* %ctx, %kcl_value_ref_t* %_args, %kcl_value_ref_t* %_kwargs);

// api-spec:       kcl_file_exists
// api-spec(c):    kcl_value_ref_t* kcl_file_exists(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_exists(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_abs
// api-spec(c):    kcl_value_ref_t* kcl_file_abs(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_abs(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_mkdir
// api-spec(c):    kcl_value_ref_t* kcl_file_mkdir(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_mkdir(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_delete
// api-spec(c):    kcl_value_ref_t* kcl_file_delete(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_delete(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_cp
// api-spec(c):    kcl_value_ref_t* kcl_file_cp(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_cp(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_mv
// api-spec(c):    kcl_value_ref_t* kcl_file_mv(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_mv(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_size
// api-spec(c):    kcl_value_ref_t* kcl_file_size(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_size(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_write
// api-spec(c):    kcl_value_ref_t* kcl_file_write(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_write(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_append
// api-spec(c):    kcl_value_ref_t* kcl_file_append(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_append(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_file_read_env
// api-spec(c):    kcl_value_ref_t* kcl_file_read_env(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_file_read_env(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_template_execute
// api-spec(c):    kcl_value_ref_t* kcl_template_execute(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_template_execute(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_template_html_escape
// api-spec(c):    kcl_value_ref_t* kcl_template_html_escape(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_template_html_escape(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

// api-spec:       kcl_runtime_catch
// api-spec(c):    kcl_value_ref_t* kcl_runtime_catch(kcl_context_t* ctx, kcl_value_ref_t* args, kcl_value_ref_t* kwargs);
// api-spec(llvm): declare %kcl_value_ref_t* @kcl_runtime_catch(%kcl_context_t* %ctx, %kcl_value_ref_t* %args, %kcl_value_ref_t* %kwargs);

