use crate::command::Command;

/// KclvmLinker is mainly responsible for linking the dylibs generated by KclvmAssembler.
pub struct KclvmLinker {}
impl KclvmLinker {
    /// Link the dylibs generated by method "gen_bc_or_ll_file".
    pub fn link_all_dylibs(dylib_paths: Vec<String>, plugin_agent: u64) -> String {
        let mut cmd = Command::new(plugin_agent);
        cmd.link_dylibs(&dylib_paths, "")
    }
}
