import nested_vendor as nv
import nested_vendor.nested_vendor as nvnv

nv_sub_in_subpkg = nv.sub_in_subpkg
nv_sub1_in_subpkg = nv.sub1_in_subpkg

nv_sub_in_sub2_in_subpkg = nv.sub_in_sub2_in_subpkg
nv_sub1_in_sub2_in_subpkg = nv.sub1_in_sub2_in_subpkg

nvnv_sub_in_subpkg = nvnv.sub_in_subpkg
nvnv_sub1_in_subpkg = nvnv.sub1_in_subpkg

nvnv_sub_in_sub2_in_subpkg = nvnv.sub_in_sub2_in_subpkg
nvnv_sub1_in_sub2_in_subpkg = nvnv.sub1_in_sub2_in_subpkg