data1 = [
    if True:
        "value1"
    elif True:
        "value2"
    elif True:
        "value3"
    else:
        "value4"
]
data2 = [
    if False:
        "value1"
    elif True:
        "value2"
    elif True:
        "value3"
    else:
        "value4"
]
data3 = [
    if False:
        "value1"
    elif False:
        "value2"
    elif True:
        "value3"
    else:
        "value4"
]
data4 = [
    if False:
        "value1"
    elif False:
        "value2"
    elif False:
        "value3"
    else:
        "value4"
]
