#!/bin/sh

# Stop on error.
set -e

# python3 path
python3_bin=`which python3`
kclvm_install_dir=$(cd `dirname $0`/..; pwd)
pip_install_done_file="$kclvm_install_dir/lib/site-packages/kclvm.requirements.done.txt"

# check python3
if [ -z "$python3_bin" ]; then
    echo "python3 not found!"
    exit 1
fi

# once: pip install
if [ ! -f $pip_install_done_file ]; then
    # check python3 version
    $python3_bin -c "import sys; sys.exit(0) if sys.version_info>=(3,7,3) else (print('please install python 3.7.3+') or sys.exit(1))"
    # pip install requirements.txt
    install_list=$kclvm_install_dir/requirements.txt
    target_dir=$kclvm_install_dir/lib/site-packages

    # kclvm pip install all libs
    $python3_bin -m pip install --target=$target_dir -r $install_list
    echo 'done' > $pip_install_done_file
fi

export PYTHONPATH=$kclvm_install_dir/lib/site-packages
export KCLVM_CLI_BIN_PATH=$kclvm_install_dir/bin
$python3_bin -m kclvm.tools.lint "$@"

