name: Build and Test on Linux ARCH64

on: ["push", "pull_request"]

jobs:
  build-and-test-arm64:
    name: Build and Test on Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull custom ARM64 Docker image
        run: |
          docker pull --platform linux/arm64 kcllang/kcl-builder-arm64

      - name: Build in Docker
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            kcllang/kcl-builder-arm64 \
            /bin/bash -c "make && make release"

      - name: Release
        shell: bash
        run: os=ubuntu topdir=$PWD ./scripts/release.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kcl-linux-arm64
          if-no-files-found: error
          path: _build/kclvm-ubuntu-latest.tar.gz
