data1 = {
    if True:
        key1: "value1"
    elif True:
        key2: "value2"
    elif True:
        key3: "value3"
    else:
        key4: "value4"
}
data2 = {
    if False:
        key1: "value1"
    elif True:
        key2: "value2"
    elif True:
        key3: "value3"
    else:
        key4: "value4"
}
data3 = {
    if False:
        key1: "value1"
    elif False:
        key2: "value2"
    elif True:
        key3: "value3"
    else:
        key4: "value4"
}
data4 = {
    if False:
        key1: "value1"
    elif False:
        key2: "value2"
    elif False:
        key3: "value3"
    else:
        key4: "value4"
}
